### ISSUE TITLE
Availability on Debian Buster / Raspberry Pi3

### ISSUE THREAD

**Issue by mariobrx** [flathub/com.dosbox_x.DOSBox-X#3]
Hi, I've been using Dosbox-X for about 2 years now. I had made myself an onorthodox installation script that copies the files from an adapted version (I found out how to uncomment certain lines to get the time synchro with host working). After the copy I only had to launch the "make install" script to get everything nicely installed. It was working great for me, but I got stuck with an older version. 
I was delighted to see that the newest version now comes with the time synchro option, so time for me to get a proper installation script. So I tried out the flatpak method but got an error: "nothing matches com.dosbox_x.DOSBox-X in remote flathub". After some searching I concluded that the com.dosbox_x.DOSBox-X package is not listed (after exporting the list to a text file: dosbox is in it, Dosbox-x isn't, see attached).
Can you please confirm that my conclusion is right and if so: could it be added in an easy way?

I also tried to install it via snap and there I got a clearer error message: "snap dosbox-x is not available on stable for this architecture (armhf) but exists on other architectures (amd64, i386)". I understood that snap is not officially supported by dosbox-x project, so no worries about that
[flat.txt](https://github.com/flathub/com.dosbox_x.DOSBox-X/files/5762440/flat.txt)
.

**Comment by rderooy** [comment]
Strange, I just tried it here on a system that does not have it installed, and the following works:
```
flatpak install com.dosbox_x.DOSBox-X
```
You should also be able to click on the install link on the flathub webpage on most Linux distributions.

**Comment by rderooy** [comment]
I missed the fact that your using a Pi3. That is 32bit ARM. Right now the flatpak is only available for 64bit x86 and ARM.

I may need to investigate what it would take to provide a 32bit ARM version through flatpak.

**Comment by mariobrx** [comment]
Thanks for confirmation, it would be really interesting to make it available on 32bit ARM, I guess there are other people that might also be interested in an easy install procedure for their Raspberry Pi. 
A beta version of 64bit Linux seems to be available for both Pi3 as Pi4, but they don't recommend to use it yet as uncomplete and unstable. I also wonder if it will ever smoothly on a Pi3 though...

**Comment by rderooy** [comment]
I remember reading that the Pi3 graphics chip has issues in 64bit mode, that cannot be solved. The Pi4 does not have this issue.

**Comment by rderooy** [comment]
@mariobrx I had a look around, and it seems that flathub dropped support for 32bit architectures with newer runtime. The last runtime to support 32bit Arm seems to be 19.08, while we are using 20.08 as you can see in the manifest.

```
flatpak remote-ls flathub --arch=arm
```

**Comment by mariobrx** [comment]
Bad news...
 I asked the same question in the snapcrafters group, I hope to get a positive answer there otherwise I'll have to stick with my old way of working.
